import os

class Config(object):
	SECRET_KEY = 'SECRET_KEY'
	PAGE_ACCESS_TOKEN = 'EAADMEPFiu3kBADUxvBLzJRFrSTU4dg5reuliZACZCHoZAX3mHo3xsnYUb0YOwDOqmF956lr58ZA09dZBHYx5ZC9OkhCBSfZA0dCoAKPMBR6iq3iHkMOE19IGnb3k4U3ZCtvBx8KlZAO3WpbqZCSiaiwCEi3UB2DND7hlCkKAUvRbQNZBT2vrv8rZC8kM'
	USER_GEONAMES = os.environ.get('USER_GEONAMES')

class DevelopmentConfig(Config):
	DEBUG = True
	